Repository rwiteshbera/Pixby, pull requests merged in 2022-10, with the labels that each got.

#6 Change wording in the Login component to make it more natural
  client/src/components/Login/Login.jsx
  package-lock.json
  server/package-lock.json
Labels: enhancement, hacktoberfest-accepted

#11 Improvement : Generate an image of contributors to keep your README.m…
  README.md
Labels: documentation, hacktoberfest-accepted

#14 Issue 12
  server/middleware/requireLogin.js
Labels: enhancement, hacktoberfest-accepted

#20 Use .then method instead of await , fix #18
  server/middleware/requireLogin.js
Labels: bug
